version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - taskapi
skip_branch_with_pr: true
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
environment:
  nodejs_version: 8
install:
- ps: >-
    npm install vsce -g


    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew clean -PjenkinsBuild -PreleaseType=OFFICIAL --continue --no-daemon
    } Else {
        ./gradlew clean -PjenkinsBuild --continue --no-daemon
    }
cache: C:\Users\appveyor\.gradle
build_script:
- ps: >-
    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew build updateVersions extractCppDependencies -PjenkinsBuild -PreleaseType=OFFICIAL --continue --no-daemon
    } Else {
        ./gradlew build updateVersions extractCppDependencies -PjenkinsBuild --continue --no-daemon
    }

    if ($lastexitcode -ne 0) {
        throw ("Exec: " + $errorMessage)
    }

    cd vscode-wpilib

    npm install

    vsce package

    if ($lastexitcode -eq 0) {
        echo $lastexitcode
    }
test: off
artifacts:
- path: '**/*.vsix'
  name: VSIX
deploy:
- provider: GitHub
  auth_token:
    secure: jecQI2sLa3l2Ubgls0IS5xeqCezIqisLyC4y8VSm7JZzXM7r+wWc7Fs7aoCQJ51G
  artifact: /.*\.*/
  on:
    appveyor_repo_tag: true
